<?php

/**
 * Implements hook_config_form().
 */
function cors_config_form() {
  $allowed_origins = variable_get('allowed_origins', array());

  $form['allowed_origins'] = [
    '#type' => 'textarea',
    '#title' => t('允许的域'),
    '#rows' => '5',
    '#default_value' => implode("\n", array_keys($allowed_origins)),
    '#description' => t('一行一个地址, 比如：http://example.com'),
  ];
  $form['form_id'] = 'cors_allowed_origins_form';
  $form['name'] = '跨域设置';

  return $form;
}

/**
 * Implements hook_config_form_submit().
 */
function cors_config_form_submit($form_state) {
  $settings = array();
  if(!empty($form_state['allowed_origins'])){
    $domains = explode("\n", $form_state['allowed_origins']);
    foreach ($domains as $domain) {
      $settings[$domain] = true;
    }
  }

  variable_set('allowed_origins', $settings);
  return true;
}
